const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');
const net = require('node:net');
let server, base, directory, fixtures;
const password = 'SenhaSegura123!';
async function call(route, data, cookie, headers = {}) {
  const response = await fetch(base + route, { method: data ? 'POST' : 'GET', headers: { ...(data ? { 'Content-Type': 'application/json' } : {}), ...(cookie ? { Cookie: cookie } : {}), ...headers }, body: data ? JSON.stringify(data) : undefined });
  const json = await response.json(); return { status: response.status, json, cookie: response.headers.get('set-cookie')?.split(';')[0] };
}
before(async () => {
  const testRoot = path.join(__dirname, '..', 'data', 'test-runs'); fs.mkdirSync(testRoot, { recursive: true });
  directory = fs.mkdtempSync(path.join(testRoot, 'changeskills-test-'));
  const probe = net.createServer(); await new Promise(resolve => probe.listen(0, '127.0.0.1', resolve)); const port = probe.address().port; await new Promise(resolve => probe.close(resolve));
  base = `http://127.0.0.1:${port}`;
  server = spawn(process.execPath, ['server.js'], { cwd: path.join(__dirname, '..'), env: { ...process.env, DATA_DIR: directory, PORT: String(port), BASE_URL: base, ADMIN_PASSWORD: password, NODE_ENV: 'test' }, stdio: ['ignore', 'pipe', 'pipe'] });
  await new Promise((resolve, reject) => { let errors = ''; server.stderr.on('data', chunk => { errors += chunk; }); const timer = setTimeout(() => reject(new Error('Startup timeout: ' + errors)), 15000); server.stdout.on('data', chunk => { if (chunk.toString().includes('disponível')) { clearTimeout(timer); resolve(); } }); server.once('exit', code => { clearTimeout(timer); reject(new Error('Server exit ' + code + ': ' + errors)); }); });
});
after(async () => {
  if (server && server.exitCode === null) { const stopped = new Promise(resolve => server.once('exit', resolve)); server.kill(); await stopped; }
  if (directory) {
    const resolved = path.resolve(directory);
    assert.ok(resolved.startsWith(path.resolve(__dirname, '..', 'data', 'test-runs') + path.sep) && path.basename(resolved).startsWith('changeskills-test-'));
    fs.rmSync(resolved, { recursive: true, force: true });
  }
});
test('autenticação, isolamento, CRUD, recuperação, arquivos e persistência', async () => {
  assert.equal((await call('/api/bootstrap')).status, 401);
  assert.equal((await call('/api/auth/login', { email: 'admin@changeskills.com.br', password: 'errada', role: 'admin' })).status, 401);
  const admin = await call('/api/auth/login', { email: 'admin@changeskills.com.br', password, role: 'admin' }); assert.equal(admin.status, 200);
  assert.match(admin.cookie, /cs_session=/);
  const register = email => call('/api/auth/register', { email, password, name: 'Gestor', schoolName: 'Escola de Teste' });
  const a = await register('a@example.com'); const b = await register('b@example.com'); assert.equal(a.status, 200); assert.equal(b.status, 200);
  assert.equal((await register('a@example.com')).status, 409);
  assert.equal((await call('/api/auth/me', null, a.cookie)).json.user.userEmail, 'a@example.com');
  assert.equal((await call('/api/rpc', { method: 'saveDB', args: [{}] }, a.cookie)).status, 400);
  assert.equal((await call('/api/rpc', { method: 'addSchool', args: [{ name: 'Ataque' }] }, a.cookie)).status, 403);
  const student = await call('/api/rpc', { method: 'addStudent', args: [{ name: 'Aluno', email: 'student@example.com', schoolId: b.json.user.schoolId }] }, a.cookie);
  assert.equal(student.json.schoolId, a.json.user.schoolId);
  assert.equal((await call('/api/bootstrap', null, b.cookie)).json.students.length, 0);
  await call('/api/rpc', { method: 'updateStudent', args: [student.json.id, { name: 'Alterado' }] }, b.cookie);
  assert.equal((await call('/api/bootstrap', null, a.cookie)).json.students[0].name, 'Aluno');
  const account = await call('/api/accounts', { name: 'Aluno', email: 'student@example.com', password, role: 'aluno' }, a.cookie); assert.equal(account.status, 200);
  const login = await call('/api/auth/login', { email: 'student@example.com', password, role: 'aluno' }); assert.equal(login.status, 200);
  assert.equal((await call('/api/rpc', { method: 'deleteStudent', args: [student.json.id] }, login.cookie)).status, 403);
  assert.equal((await call('/api/rpc', { method: 'addStudent', args: [{ name: 'CSRF' }] }, a.cookie, { Origin: 'https://evil.example' })).status, 403);
  const upload = await call('/api/files', { name: 'teste.pdf', base64: Buffer.from('%PDF-test').toString('base64') }, login.cookie); assert.equal(upload.status, 200);
  assert.equal((await fetch(base + upload.json.url, { headers: { Cookie: b.cookie } })).status, 404);
  assert.equal(await (await fetch(base + upload.json.url, { headers: { Cookie: login.cookie } })).text(), '%PDF-test');
  const forgot = await call('/api/auth/forgot-password', { email: 'student@example.com' }); assert.equal(forgot.status, 200); assert.equal(forgot.json.token, undefined);
  const mailFile = fs.readdirSync(path.join(directory, 'mail'))[0]; const email = JSON.parse(fs.readFileSync(path.join(directory, 'mail', mailFile), 'utf8')); const token = email.text.split('/reset/')[1];
  const newPassword = 'OutraSenhaSegura456!';
  assert.equal((await call('/api/auth/reset-password', { token, password: newPassword })).status, 200);
  assert.equal((await call('/api/auth/reset-password', { token, password: newPassword })).status, 400);
  assert.equal((await call('/api/auth/me', null, login.cookie)).status, 401);
  assert.equal((await call('/api/auth/login', { email: 'student@example.com', password: newPassword, role: 'aluno' })).status, 200);
  const freshStudent = await call('/api/auth/login', { email: 'student@example.com', password: newPassword, role: 'aluno' });
  const teacherAccount = await call('/api/accounts', { name: 'Professor', email: 'teacher@example.com', password, role: 'professor', schoolId: a.json.user.schoolId }, admin.cookie); assert.equal(teacherAccount.status, 200);
  const teacher = await call('/api/auth/login', { email: 'teacher@example.com', password, role: 'professor' }); assert.equal(teacher.status, 200);
  const course = await call('/api/rpc', { method: 'addCourse', args: [{ name: 'Curso Teste', schoolId: a.json.user.schoolId, teacherId: teacher.json.user.userId }] }, admin.cookie); assert.equal(course.status, 200);
  const moduleId = course.json.modules[0].id;
  const activity = await call('/api/rpc', { method: 'addActivityToModule', args: [course.json.id, moduleId, { title: 'Exercício', maxGrade: 10 }] }, admin.cookie); assert.equal(activity.status, 200);
  const submit = await call('/api/rpc', { method: 'submitStudentActivity', args: [course.json.id, moduleId, activity.json.id, { studentId: 'outro-aluno', studentName: 'Falso', fileName: 'teste.pdf' }] }, freshStudent.cookie);
  assert.equal(submit.json.studentId, student.json.id);
  const attach = await call('/api/attachments', { courseId: course.json.id, moduleId, itemId: activity.json.id, fileId: upload.json.id }, freshStudent.cookie); assert.equal(attach.status, 200);
  const gradeData = { courseId: course.json.id, moduleId, itemId: activity.json.id, studentId: student.json.id, grade: 8.5, feedback: 'Muito bom' };
  assert.equal((await call('/api/grades', gradeData, freshStudent.cookie)).status, 403);
  assert.equal((await call('/api/grades', gradeData, b.cookie)).status, 403);
  assert.equal((await call('/api/grades', gradeData, admin.cookie)).json.grade, 8.5);
  const studentView = (await call('/api/bootstrap', null, freshStudent.cookie)).json;
  assert.equal(studentView.courses[0].modules[0].items[0].submissions[0].grade, 8.5);
  assert.equal((await call('/api/messages', { recipientId: teacherAccount.json.user.userId, text: 'Olá, professor!' }, freshStudent.cookie)).status, 200);
  assert.equal((await call('/api/messages', null, teacher.cookie)).json.length, 1);
  assert.equal((await call('/api/messages', null, b.cookie)).json.length, 0);
  assert.equal((await call('/api/profile', { name: 'Aluno Atualizado', phone: '11999999999', language: 'Português' }, freshStudent.cookie)).json.user.userName, 'Aluno Atualizado');
  assert.equal((await call('/api/rpc', { method: 'addStudent', args: [{ name: '<img src=x onerror=alert(1)>' }] }, a.cookie)).status, 400);
  assert.equal((await call('/api/rpc', { method: 'updateSchool', args: [a.json.user.schoolId, { primaryColor: 'red; color: black' }] }, a.cookie)).status, 400);
  const disk = JSON.parse(fs.readFileSync(path.join(directory, 'database.json'), 'utf8')); assert.equal(disk.users.length, 5); assert.ok(!disk.users.some(u => u.password)); assert.ok(!fs.readFileSync(path.join(directory, 'database.json'), 'utf8').includes(newPassword));
  fixtures = { admin, b, teacher, student: freshStudent, studentId: student.json.id, schoolId: a.json.user.schoolId, course: course.json, moduleId, itemId: activity.json.id };
  for (const route of ['/data/database.json', '/.env', '/server.js', '/package.json']) assert.equal((await fetch(base + route)).status, 404);
  assert.equal((await call('/api/auth/logout', {}, a.cookie)).status, 200); assert.equal((await call('/api/auth/me', null, a.cookie)).status, 401);
});
test('validação dos cadastros, cobrança por aluno e nota zero', async () => {
  const school = await call('/api/auth/login', { email: 'a@example.com', password, role: 'escola' }); assert.equal(school.status, 200);
  fixtures.school = school;
  const rpc = (method, args, cookie = school.cookie) => call('/api/rpc', { method, args }, cookie);
  const other = await rpc('addStudent', [{ name: 'Aluno Atualizado', email: 'other@example.com' }]); assert.equal(other.status, 200);
  const ownCharge = await rpc('addFinancial', [{ studentId: fixtures.studentId, studentName: 'Aluno Atualizado', value: 100 }]); assert.equal(ownCharge.status, 200);
  const otherCharge = await rpc('addFinancial', [{ studentId: other.json.id, studentName: 'Aluno Atualizado', value: 200 }]); assert.equal(otherCharge.status, 200);
  assert.equal((await rpc('addFinancial', [{ studentName: 'Aluno Atualizado', value: 100 }])).status, 400);
  assert.equal((await rpc('addFinancial', [{ studentId: 'aluno-1', value: 100 }])).status, 400);
  assert.equal((await rpc('addFinancial', [{ studentId: fixtures.studentId, value: -100 }])).status, 400);
  const studentData = (await call('/api/bootstrap', null, fixtures.student.cookie)).json;
  assert.deepEqual(studentData.financial.map(f => f.id), [ownCharge.json.id]);
  assert.deepEqual((await call('/api/bootstrap', null, fixtures.teacher.cookie)).json.financial, []);
  assert.equal((await rpc('updateCourse', [fixtures.course.id, { modules: 'inválido' }], fixtures.admin.cookie)).status, 400);
  assert.equal((await rpc('addCourse', [{ name: 'Professor de outra escola', teacherId: 'prof-1', schoolId: fixtures.schoolId }], fixtures.admin.cookie)).status, 400);
  assert.equal((await rpc('updateSchool', [fixtures.schoolId, { plan: 'Enterprise' }])).status, 403);
  const grade = { courseId: fixtures.course.id, moduleId: fixtures.moduleId, itemId: fixtures.itemId, studentId: fixtures.studentId, grade: '' };
  assert.equal((await call('/api/grades', grade, fixtures.admin.cookie)).status, 400);
  assert.equal((await call('/api/grades', { ...grade, grade: 0, feedback: 'Refazer exercício' }, fixtures.admin.cookie)).json.grade, 0);
  assert.equal((await call('/api/files', { name: 'arquivo.pdf', base64: 'not-base64!' }, fixtures.student.cookie)).status, 400);
  assert.equal((await call('/api/files', { name: '<script>.pdf', base64: 'YQ==' }, fixtures.student.cookie)).status, 400);
  const beforeRead = fs.readFileSync(path.join(directory, 'database.json'), 'utf8');
  assert.equal((await rpc('getStudents', [], school.cookie)).status, 200);
  assert.equal(fs.readFileSync(path.join(directory, 'database.json'), 'utf8'), beforeRead);
});
test('bloqueio de login, sincronização de e-mail e edição atômica do perfil', async () => {
  const rpc = (method, args) => call('/api/rpc', { method, args }, fixtures.school.cookie);
  const wrongPassword = await call('/api/profile', { name: 'Nome que não deve salvar', currentPassword: 'senha errada', newPassword: 'NovaSenhaSegura123!' }, fixtures.student.cookie);
  assert.equal(wrongPassword.status, 400);
  assert.equal((await call('/api/auth/me', null, fixtures.student.cookie)).json.user.userName, 'Aluno Atualizado');
  assert.equal((await rpc('updateStudent', [fixtures.studentId, { email: 'changed@example.com' }])).status, 200);
  assert.equal((await call('/api/auth/login', { email: 'student@example.com', password: 'OutraSenhaSegura456!', role: 'aluno' })).status, 401);
  const changed = await call('/api/auth/login', { email: 'changed@example.com', password: 'OutraSenhaSegura456!', role: 'aluno' }); assert.equal(changed.status, 200);
  assert.equal((await rpc('updateStudent', [fixtures.studentId, { email: 'teacher@example.com' }])).status, 409);
  await rpc('updateStudent', [fixtures.studentId, { status: 'Bloqueado' }]);
  assert.equal((await call('/api/auth/login', { email: 'changed@example.com', password: 'OutraSenhaSegura456!', role: 'aluno' })).status, 403);
  assert.equal((await call('/api/bootstrap', null, changed.cookie)).status, 403);
  await rpc('updateStudent', [fixtures.studentId, { status: 'Ativo', email: 'student@example.com' }]);
  const login = await call('/api/auth/login', { email: 'student@example.com', password: 'OutraSenhaSegura456!', role: 'aluno' }); assert.equal(login.status, 200);
  const profile = await call('/api/profile', { name: 'Aluno Atualizado', currentPassword: 'OutraSenhaSegura456!', newPassword: 'SenhaPerfilSegura789!' }, login.cookie); assert.equal(profile.status, 200); assert.equal(profile.json.passwordChanged, true);
  assert.equal((await call('/api/auth/me', null, login.cookie)).status, 401);
});
test('o banco e as contas sobrevivem à reinicialização do processo', async () => {
  const stopped = new Promise(resolve => server.once('exit', resolve)); server.kill(); await stopped;
  server = spawn(process.execPath, ['server.js'], { cwd: path.join(__dirname, '..'), env: { ...process.env, DATA_DIR: directory, PORT: new URL(base).port, BASE_URL: base, NODE_ENV: 'test' }, stdio: ['ignore', 'pipe', 'pipe'] });
  await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('Restart timeout')), 15000); server.stdout.on('data', chunk => { if (chunk.toString().includes('disponível')) { clearTimeout(timer); resolve(); } }); server.once('exit', code => { clearTimeout(timer); reject(new Error('Exit ' + code)); }); });
  const login = await call('/api/auth/login', { email: 'student@example.com', password: 'SenhaPerfilSegura789!', role: 'aluno' }); assert.equal(login.status, 200);
  const data = await call('/api/bootstrap', null, login.cookie); assert.equal(data.json.students[0].name, 'Aluno Atualizado'); assert.equal(data.json.courses[0].modules[0].items[0].submissions[0].grade, 0);
});
test('CRUD de contas, hashes individuais e revogação de credenciais', async () => {
  const school = await call('/api/auth/login', { email: 'a@example.com', password, role: 'escola' });
  const student = await call('/api/auth/login', { email: 'student@example.com', password: 'SenhaPerfilSegura789!', role: 'aluno' });
  assert.equal((await call('/api/accounts', null, student.cookie)).status, 403);
  assert.equal((await call('/api/accounts', null, fixtures.teacher.cookie)).status, 403);
  assert.equal((await call('/api/auth/register', { name: 'Teste', schoolName: 'Teste', email: 'weak@example.com', password: '123' })).status, 400);
  assert.equal((await call('/api/auth/login', { email: 'a@example.com', password: {} })).status, 401);
  const create = data => call('/api/accounts', { name: 'Usuário CRUD', email: 'crud@example.com', password, role: 'aluno', ...data }, school.cookie);
  assert.equal((await create({ name: ' ' })).status, 400);
  assert.equal((await create({ role: 'admin' })).status, 400);
  const account = await create({}); assert.equal(account.status, 200);
  assert.equal((await create({ email: ' CRUD@EXAMPLE.COM ' })).status, 409);
  const accountId = account.json.user.id;
  const disk = JSON.parse(fs.readFileSync(path.join(directory, 'database.json'), 'utf8'));
  const hashA = disk.users.find(u => u.id === accountId).passwordHash;
  const hashB = disk.users.find(u => u.email === 'a@example.com').passwordHash;
  assert.match(hashA, /^[a-f0-9]{32}:[a-f0-9]{128}$/); assert.notEqual(hashA, hashB);
  assert.ok(!JSON.stringify(disk).includes(password));
  const listing = await call('/api/accounts', null, school.cookie);
  assert.ok(listing.json.some(u => u.id === accountId)); assert.ok(listing.json.every(u => u.schoolId === school.json.user.schoolId));
  assert.ok(!JSON.stringify(listing.json).includes('passwordHash'));
  const update = data => call('/api/accounts/update', { id: accountId, ...data }, school.cookie);
  assert.equal((await call('/api/accounts/update', { id: accountId, name: 'Intruso' }, fixtures.b.cookie)).status, 404);
  assert.equal((await call('/api/accounts/delete', { id: accountId }, student.cookie)).status, 403);
  assert.equal((await update({ role: 'admin' })).status, 400);
  assert.equal((await update({ email: 'teacher@example.com' })).status, 409);
  const firstLogin = await call('/api/auth/login', { email: 'crud@example.com', password }); assert.equal(firstLogin.status, 200);
  const recoveryToken = async email => {
    assert.equal((await call('/api/auth/forgot-password', { email })).status, 200);
    const messages = fs.readdirSync(path.join(directory, 'mail')).map(f => JSON.parse(fs.readFileSync(path.join(directory, 'mail', f), 'utf8'))).filter(m => m.to === email);
    return messages.at(-1).text.split('/reset/')[1];
  };
  const oldEmailToken = await recoveryToken('crud@example.com');
  assert.equal((await update({ name: 'Nome editado', email: 'crud-new@example.com' })).status, 200);
  assert.equal((await call('/api/auth/me', null, firstLogin.cookie)).status, 401);
  assert.equal((await call('/api/auth/reset-password', { token: oldEmailToken, password })).status, 400);
  assert.equal((await call('/api/auth/login', { email: 'crud@example.com', password })).status, 401);
  const renamedLogin = await call('/api/auth/login', { email: 'crud-new@example.com', password }); assert.equal(renamedLogin.json.user.userName, 'Nome editado');
  const oldPasswordToken = await recoveryToken('crud-new@example.com');
  const nextPassword = 'NovaSenhaCrud456!';
  assert.equal((await call('/api/auth/change-password', { currentPassword: password, password: nextPassword }, renamedLogin.cookie)).status, 200);
  assert.equal((await call('/api/auth/me', null, renamedLogin.cookie)).status, 401);
  assert.equal((await call('/api/auth/reset-password', { token: oldPasswordToken, password })).status, 400);
  const newLogin = await call('/api/auth/login', { email: 'crud-new@example.com', password: nextPassword }); assert.equal(newLogin.status, 200);
  const blockToken = await recoveryToken('crud-new@example.com');
  assert.equal((await update({ active: false })).status, 200);
  assert.equal((await call('/api/auth/me', null, newLogin.cookie)).status, 401);
  assert.equal((await call('/api/auth/login', { email: 'crud-new@example.com', password: nextPassword })).status, 401);
  assert.equal((await call('/api/auth/reset-password', { token: blockToken, password })).status, 400);
  assert.equal((await update({ active: true })).status, 200);
  const restored = await call('/api/auth/login', { email: 'crud-new@example.com', password: nextPassword }); assert.equal(restored.status, 200);
  const deleteToken = await recoveryToken('crud-new@example.com');
  assert.equal((await call('/api/accounts/delete', { id: accountId }, fixtures.b.cookie)).status, 404);
  assert.equal((await call('/api/accounts/delete', { id: accountId }, school.cookie)).status, 200);
  assert.equal((await call('/api/auth/me', null, restored.cookie)).status, 401);
  assert.equal((await call('/api/auth/reset-password', { token: deleteToken, password })).status, 400);
  assert.ok(!(await call('/api/accounts', null, school.cookie)).json.some(u => u.id === accountId));
  const recreated = await create({ email: 'crud-new@example.com' }); assert.equal(recreated.status, 200); assert.equal(recreated.json.user.userId, account.json.user.userId);
  const unknown = await call('/api/auth/forgot-password', { email: 'unknown@example.com' });
  const known = await call('/api/auth/forgot-password', { email: 'crud-new@example.com' }); assert.deepEqual(unknown.json, known.json);
});
test('curso completo: matrícula, rascunhos, aulas, materiais, entrega, correção e exclusão', async () => {
  const school = await call('/api/auth/login', { email: 'a@example.com', password });
  const student = await call('/api/auth/login', { email: 'student@example.com', password: 'SenhaPerfilSegura789!' });
  const teacher = await call('/api/auth/login', { email: 'teacher@example.com', password });
  await call('/api/accounts', { name: 'Outro professor', email: 'second-teacher@example.com', password, role: 'professor', schoolId: fixtures.schoolId }, fixtures.admin.cookie);
  await call('/api/accounts', { name: 'Outro aluno', email: 'other@example.com', password, role: 'aluno' }, school.cookie);
  const otherTeacher = await call('/api/auth/login', { email: 'second-teacher@example.com', password });
  const otherStudent = await call('/api/auth/login', { email: 'other@example.com', password });
  const action = (name, input, cookie = fixtures.admin.cookie) => call('/api/learning/' + name, input, cookie);
  const courseFields = { schoolId: fixtures.schoolId, teacherId: teacher.json.user.userId, title: 'Curso completo de teste', description: "Teacher's guide: <b>texto simples</b>", studentIds: [fixtures.studentId], published: false };
  const created = await action('course', courseFields); assert.equal(created.status, 200);
  const courseId = created.json.id;
  assert.equal(created.json.teacherId, teacher.json.user.userId);
  assert.ok(!(await call('/api/bootstrap', null, student.cookie)).json.courses.some(c => c.id === courseId));
  assert.equal((await action('course', { ...courseFields, courseId }, otherTeacher.cookie)).status, 403);
  assert.equal((await action('course', { ...courseFields, courseId }, fixtures.b.cookie)).status, 403);
  assert.equal((await action('course', { ...courseFields, courseId }, student.cookie)).status, 403);
  assert.equal((await action('course', { ...courseFields, courseId, published: true })).status, 200);
  assert.ok((await call('/api/bootstrap', null, student.cookie)).json.courses.some(c => c.id === courseId));
  assert.ok(!(await call('/api/bootstrap', null, otherStudent.cookie)).json.courses.some(c => c.id === courseId));
  const mod = await action('module', { courseId, title: 'Módulo inicial', description: '' }); assert.equal(mod.status, 200);
  const moduleId = mod.json.id;
  assert.equal((await action('module', { courseId, moduleId, title: 'Módulo editado', description: 'Descrição atualizada' })).json.title, 'Módulo editado');
  const lessonFields = { courseId, moduleId, type: 'lesson', title: 'Aula gravada', description: "Let's learn.", duration: '10 min', videoUrl: 'https://example.com/aula.mp4', published: true };
  assert.equal((await action('item', { ...lessonFields, videoUrl: '' })).status, 400);
  assert.equal((await action('item', { ...lessonFields, videoUrl: 'javascript:alert(1)' })).status, 400);
  const lesson = await action('item', lessonFields); assert.equal(lesson.status, 200); const lessonId = lesson.json.id;
  const draft = await action('item', { ...lessonFields, title: 'Rascunho', videoUrl: '', published: false }); assert.equal(draft.status, 200);
  assert.equal((await action('completion', { courseId, moduleId, itemId: draft.json.id, completed: true }, student.cookie)).status, 404);
  assert.equal((await action('completion', { courseId, moduleId, itemId: lessonId, completed: true }, otherStudent.cookie)).status, 404);
  assert.equal((await action('completion', { courseId, moduleId, itemId: lessonId, completed: true }, student.cookie)).status, 200);
  assert.equal((await action('completion', { courseId, moduleId, itemId: lessonId, completed: true }, student.cookie)).status, 200);
  let visible = (await call('/api/bootstrap', null, student.cookie)).json.courses.find(c => c.id === courseId);
  assert.equal(visible.studentIds, undefined);
  assert.equal(visible.modules[0].items.length, 1); assert.deepEqual(visible.modules[0].items[0].completedBy, [fixtures.studentId]);
  const uploaded = await call('/api/files', { schoolId: fixtures.schoolId, name: 'apostila.pdf', base64: Buffer.from('%PDF-1.4 exemplo').toString('base64') }, fixtures.admin.cookie); assert.equal(uploaded.status, 200);
  const material = await action('material', { courseId, moduleId, itemId: lessonId, title: 'Apostila', fileId: uploaded.json.id }); assert.equal(material.status, 200);
  assert.equal((await fetch(base + uploaded.json.url, { headers: { Cookie: student.cookie } })).status, 200);
  assert.equal((await fetch(base + uploaded.json.url, { headers: { Cookie: otherStudent.cookie } })).status, 404);
  assert.equal((await action('item', { ...lessonFields, itemId: lessonId, published: false })).status, 200);
  assert.equal((await fetch(base + uploaded.json.url, { headers: { Cookie: student.cookie } })).status, 404);
  assert.equal((await action('item', { ...lessonFields, itemId: lessonId })).status, 200);
  assert.equal((await action('material', { courseId, moduleId, itemId: lessonId, materialId: material.json.id, title: 'Apostila revisada', fileId: uploaded.json.id })).json.title, 'Apostila revisada');
  const activityFields = { courseId, moduleId, type: 'activity', title: 'Atividade escrita', statement: "Write: I'm studying.", evaluationCriteria: 'Clareza', maxGrade: 10, hasGrade: true, dueDate: '', startDate: '', published: true };
  const activity = await action('item', activityFields); assert.equal(activity.status, 200); const itemId = activity.json.id;
  const assignment = { courseId, moduleId, itemId };
  assert.equal((await action('submit', { ...assignment, notes: '' }, student.cookie)).status, 400);
  assert.equal((await action('submit', { ...assignment, notes: 'Ataque' }, otherStudent.cookie)).status, 404);
  assert.equal((await action('submit', { ...assignment, notes: 'Resposta', fileId: uploaded.json.id }, student.cookie)).status, 404);
  const studentFile = await call('/api/files', { name: 'resposta.txt', base64: Buffer.from('My answer').toString('base64') }, student.cookie);
  const submission = await action('submit', { ...assignment, notes: "I'm studying.", fileId: studentFile.json.id, studentId: 'forged' }, student.cookie); assert.equal(submission.status, 200); assert.equal(submission.json.studentId, fixtures.studentId);
  assert.equal((await fetch(base + studentFile.json.url, { headers: { Cookie: teacher.cookie } })).status, 200);
  assert.equal((await fetch(base + studentFile.json.url, { headers: { Cookie: otherTeacher.cookie } })).status, 404);
  assert.equal((await action('grade', { ...assignment, studentId: fixtures.studentId, grade: 0 }, student.cookie)).status, 403);
  assert.equal((await action('grade', { ...assignment, studentId: fixtures.studentId, grade: 11 })).status, 400);
  assert.equal((await action('grade', { ...assignment, studentId: fixtures.studentId, grade: '', feedback: '' })).status, 400);
  const graded = await action('grade', { ...assignment, studentId: fixtures.studentId, grade: 0, feedback: "Let's try again." }); assert.equal(graded.status, 200); assert.equal(graded.json.grade, 0);
  const stopped = new Promise(resolve => server.once('exit', resolve)); server.kill(); await stopped;
  server = spawn(process.execPath, ['server.js'], { cwd: path.join(__dirname, '..'), env: { ...process.env, DATA_DIR: directory, PORT: new URL(base).port, BASE_URL: base, NODE_ENV: 'test' }, stdio: ['ignore', 'pipe', 'pipe'] });
  await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('Academic restart timeout')), 15000); server.stdout.on('data', chunk => { if (chunk.toString().includes('disponível')) { clearTimeout(timer); resolve(); } }); server.once('exit', code => { clearTimeout(timer); reject(new Error('Academic restart exit ' + code)); }); });
  const restoredCourse = (await call('/api/bootstrap', null, teacher.cookie)).json.courses.find(c => c.id === courseId);
  assert.equal(restoredCourse.modules[0].items.find(i => i.id === itemId).submissions[0].grade, 0);
  assert.equal(restoredCourse.modules[0].items.find(i => i.id === itemId).submissions[0].feedback, "Let's try again.");
  assert.deepEqual(restoredCourse.modules[0].items.find(i => i.id === lessonId).completedBy, [fixtures.studentId]);
  assert.equal((await fetch(base + studentFile.json.url, { headers: { Cookie: teacher.cookie } })).status, 200);
  assert.equal((await action('submit', { ...assignment, notes: 'Novo envio' }, student.cookie)).status, 409);
  assert.equal((await action('reopen', { ...assignment, studentId: fixtures.studentId })).status, 200);
  assert.equal((await action('submit', { ...assignment, notes: 'Resposta revisada' }, student.cookie)).status, 200);
  visible = (await call('/api/bootstrap', null, student.cookie)).json.courses.find(c => c.id === courseId);
  assert.equal(visible.modules[0].items.find(i => i.id === itemId).submissions.length, 1);
  assert.equal((await action('item', { ...activityFields, itemId, dueDate: '2020-01-01' })).status, 200);
  assert.equal((await action('submit', { ...assignment, notes: 'Atrasado' }, student.cookie)).status, 400);
  assert.equal((await action('item', { ...activityFields, itemId, dueDate: '2020-01-01', allowLate: true })).status, 200);
  assert.equal((await action('submit', { ...assignment, notes: 'Atrasado autorizado' }, student.cookie)).status, 200);
  assert.equal((await action('item', { ...activityFields, itemId, startDate: '2099-01-01' })).status, 200);
  assert.equal((await action('submit', { ...assignment, notes: 'Antes da abertura' }, student.cookie)).status, 400);
  assert.equal((await action('item', { ...activityFields, itemId, dueDate: '2026-02-31' })).status, 400);
  assert.equal((await action('item', { ...activityFields, itemId, hasGrade: false })).status, 200);
  assert.equal((await action('grade', { ...assignment, studentId: fixtures.studentId, feedback: 'Concluído sem nota' })).json.grade, null);
  assert.equal((await action('move-item', { ...assignment, direction: 'up' })).status, 200);
  assert.equal((await action('delete-material', { courseId, moduleId, itemId: lessonId, materialId: material.json.id })).status, 200);
  assert.equal((await fetch(base + uploaded.json.url, { headers: { Cookie: student.cookie } })).status, 404);
  assert.equal((await action('delete-item', assignment)).status, 200);
  assert.equal((await action('delete-module', { courseId, moduleId })).status, 200);
  assert.equal((await action('delete-course', { courseId })).status, 200);
  assert.ok(!(await call('/api/bootstrap', null, student.cookie)).json.courses.some(c => c.id === courseId));
});
test('catálogo central: escolas autorizadas, alunos, arquivos, isolamento e revogação', async () => {
  const admin = fixtures.admin.cookie, school = fixtures.school.cookie;
  const partner = fixtures.b;
  const learner = await call('/api/accounts', { name: 'Aluno parceiro', email: 'partner-student@example.com', password, role: 'aluno' }, partner.cookie);
  assert.equal(learner.status, 200);
  const login = await call('/api/auth/login', { email: 'partner-student@example.com', password });
  const fields = { title: 'Catálogo Change Skills', description: 'Curso central', schoolIds: [fixtures.schoolId], published: true };
  const create = await call('/api/learning/course', fields, admin); assert.equal(create.status, 200);
  const courseId = create.json.id;
  assert.ok((await call('/api/bootstrap', null, school)).json.courses.some(c => c.id === courseId));
  assert.ok(!(await call('/api/bootstrap', null, login.cookie)).json.courses.some(c => c.id === courseId));
  for (const cookie of [school, partner.cookie, fixtures.teacher.cookie]) {
    assert.equal((await call('/api/learning/course', { ...fields, courseId }, cookie)).status, 403);
    assert.equal((await call('/api/rpc', { method: 'addCourse', args: [{ name: 'Não permitido' }] }, cookie)).status, 403);
  }
  assert.equal((await call('/api/accounts', { name: 'Docente', email: 'forbidden@example.com', password, role: 'professor' }, school)).status, 403);
  assert.equal((await call('/api/rpc', { method: 'addTeacher', args: [{ name: 'Docente' }] }, school)).status, 403);
  assert.equal((await call('/api/learning/course', { ...fields, courseId, schoolIds: ['inexistente'] }, admin)).status, 400);
  fields.schoolIds.push(partner.json.user.schoolId);
  assert.equal((await call('/api/learning/course', { ...fields, courseId }, admin)).status, 200);
  const module = await call('/api/learning/module', { courseId, title: 'Módulo' }, admin);
  const moduleId = module.json.id;
  const item = await call('/api/learning/item', { courseId, moduleId, type: 'lesson', title: 'Conteúdo', videoUrl: 'https://example.com/video.mp4', published: true }, admin);
  const itemId = item.json.id;
  const upload = await call('/api/files', { name: 'central.pdf', base64: Buffer.from('%PDF-test').toString('base64') }, admin);
  assert.equal((await call('/api/learning/material', { courseId, moduleId, itemId, title: 'Material central', fileId: upload.json.id }, admin)).status, 200);
  assert.equal((await fetch(base + upload.json.url, { headers: { Cookie: login.cookie } })).status, 200);
  assert.equal((await call('/api/learning/completion', { courseId, moduleId, itemId, completed: true }, login.cookie)).status, 200);
  const schoolView = (await call('/api/bootstrap', null, school)).json.courses.find(c => c.id === courseId);
  assert.deepEqual(schoolView.modules[0].items[0].completedBy, []);
  assert.equal(schoolView.schoolIds, undefined);
  fields.schoolIds = [fixtures.schoolId];
  assert.equal((await call('/api/learning/course', { ...fields, courseId }, admin)).status, 200);
  assert.ok(!(await call('/api/bootstrap', null, login.cookie)).json.courses.some(c => c.id === courseId));
  assert.equal((await call('/api/learning/completion', { courseId, moduleId, itemId, completed: false }, login.cookie)).status, 404);
  assert.equal((await fetch(base + upload.json.url, { headers: { Cookie: login.cookie } })).status, 404);
  assert.equal((await call('/api/learning/course', { ...fields, courseId, published: false }, admin)).status, 200);
  assert.ok(!(await call('/api/bootstrap', null, school)).json.courses.some(c => c.id === courseId));
  assert.equal((await call('/api/learning/delete-course', { courseId }, admin)).status, 200);
});

test('auditoria: prefixo publicado, configurações, exportação, e-mails e proteção das rotas', async () => {
  const admin = fixtures.admin.cookie, school = fixtures.school.cookie;
  const routes = ['/auth/me','/bootstrap','/admin/settings','/accounts','/messages','/export'];
  for (const route of routes) assert.equal((await fetch(base + '/whitelabel/api' + route)).status, 401, route);
  assert.equal((await call('/whitelabel/api/auth/me', null, admin)).status, 200);
  assert.equal((await fetch(base + '/whitelabel/backend-client.js')).status, 200);
  assert.equal((await fetch(base + '/whitelabel/style.css')).status, 200);
  assert.equal((await fetch(base + '/whitelabel/server.js')).status, 404);
  assert.equal((await call('/api/admin/settings', { tab:'general',values:[{value:'Teste auditoria',checked:true}] }, admin)).status, 200);
  assert.equal((await call('/api/admin/settings', null, admin)).json.general[0].value,'Teste auditoria');
  assert.equal((await call('/api/admin/settings', null, school)).status,403);
  assert.equal((await call('/api/admin/settings', {tab:'invalido',values:[]},admin)).status,400);
  for(const collection of ['schools','students','teachers','financial']) {
    const r=await fetch(base+'/whitelabel/api/export?collection='+collection,{headers:{Cookie:school}});
    assert.equal(r.status,200);assert.match(r.headers.get('content-type'),/text\/csv/);assert.match(r.headers.get('content-disposition'),/attachment/);await r.text();
  }
  assert.equal((await call('/api/export?collection=users',null,admin)).status,400);
  assert.equal((await call('/api/email/test',{},school)).status,200);
  const charge=(await call('/api/bootstrap',null,school)).json.financial[0];
  assert.ok(charge);assert.equal((await call('/api/email/receipt',{financialId:charge.id},school)).status,200);
  assert.equal((await call('/api/email/receipt',{financialId:'missing'},school)).status,404);
  const mailFiles=fs.readdirSync(path.join(directory,'mail')).map(f=>JSON.parse(fs.readFileSync(path.join(directory,'mail',f))));
  assert.ok(mailFiles.some(m=>m.subject.includes('Teste de e-mail')));assert.ok(mailFiles.some(m=>m.subject.includes('Comprovante financeiro')));
  assert.equal((await call('/api/missing',null,admin)).status,404);
});
